# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'


    session:
        # Active la gestion de session avec les options par défaut
        handler_id: null
        cookie_secure: auto
        cookie_samesite: 'lax'
        cookie_httponly: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file





